### PR TITLE
De la guardo setup clojure 34

### PR DESCRIPTION
**Pull request by seancorfield**
Update CLI to 1.10.3.1029 for CI and manually install `tools.tools` so `clojure -Ttools` works.

This is a workaround for https://github.com/DeLaGuardo/setup-clojure/issues/34

### CODE REVIEW

**Comment by seancorfield** [comment]
Ugh! I should have rebased that against master after updating it. I guess you can squash it to a single commit in the PR?

**Comment by vemv** [comment]
Hey there!

First of all kudos for the debugging rampage 👏

What would you think of PRing against `setup-clojure`?

I wouldn't mind keeping nvd-clojure red for a while - in the end I know that all tests are passing.

**Comment by seancorfield** [comment]
I don't know enough TypeScript to submit a PR against `setup-clojure` 😄  I created an issue there (linked above) and DeLaGuardo said he'd take a look later today.

Definitely sounds reasonable at this point to keep nvd-clojure red until `setup-clojure` is fixed so feel free to close this out.

**Comment by rm-hull** [comment]
@seancorfield dont worry about the commits on the branch, we usually squash/merge anyway

**Review by vemv — APPROVED** [review]

**Comment by vemv** [comment]
The diff is small enough that it can be easily reverted later.

Thanks again for the efforts! 😊

**Pull request merged**
