### PR TITLE
Report transitive dependency paths for vulnerable artifacts.

### PR DESCRIPTION
**Pull request by jumarko**
So it's more clear where the vulnerable artifact comes from.
Still WORK IN PROGRESS - should report full dependency name
including a group id, not just an artifact id

### CODE REVIEW

**Comment by vemv** [comment]
FWIW, I routinely use `lein deps :tree` for this and other purposes. Does the job well.

**Comment by jumarko** [comment]
@vemv Sure `lein deps :tree` could be used but it's quite lot of work.
Typically, you get several (or many) reported vulnerabilities and the output produced by lein nvd is much less actionable without actually knowing that first-level dependency brings in the vulnerable artifact.

**Comment by sbalaji-opentext** [comment]
Hi , 
I am trying to run the "lein nvd check" to get the vulnerabilities for one of my projects, but getting the below error. Could you please suggest.

15:06:54  | zookeeper-3.5.1-alpha.jar                                                                        | [33m[1mCVE-2016-5017[0m, [33m[1mCVE-2017-5637[0m, [33m[1mCVE-2018-8012[0m, [33m[1mCVE-2019-0201[0m                                        |
15:06:54  +--------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
15:06:54  
15:06:54  148 vulnerabilities detected. Severity: [31m[1mHIGH[0m
15:06:54  Detailed reports saved in: [1m/home/jenkins/workspace/github_conflux_nvd/target/nvd[0m
15:06:54  
15:06:54  [35m[1m   *** THIS REPORT IS WITHOUT WARRANTY ***[0m
15:06:54  Sep 11, 2020 9:36:48 AM org.apache.commons.jcs.engine.control.CompositeCacheManager run
15:06:54  INFO: Shutdown hook activated.  Shutdown was not called.  Shutting down JCS.
15:06:54  [Pipeline] }
15:06:54  [Pipeline] // stage
15:06:54  [Pipeline] error
15:06:54  [Pipeline] }
15:06:54  [Pipeline] // node
15:06:54  [Pipeline] }
15:06:54  [Pipeline] // timestamps
15:06:54  [Pipeline] End of Pipeline
15:06:54  
15:06:54  GitHub has been notified of this commit’s build result
15:06:54  
15:06:54  ERROR: hudson.AbortException: script returned exit code 255
15:06:54  Finished: FAILURE

**Comment by sbalaji-opentext** [comment]
Below is the command that I am running. 

sh './lein nvd check --fail-threshold 11'

**Comment by slipset** [comment]
Would really love seeing this merged

**Comment by rm-hull** [comment]
@jumarko any interest in getting this PR over the line? If not please feel free to close it. Thanks!

**Comment by jumarko** [comment]
I might pick this up in near feature. I really needed this but got side-tracked by other things.
I'll let you know within one month.

**Comment by vemv** [comment]
I've realised that this PR's proposal would go against the insights and new API options reflected in https://github.com/rm-hull/lein-nvd/tree/2493010bb61ea1cbd84a8f18ead45fe0ea2a874d#avoiding-classpath-interference

(in all fairness, this PR predates those insights by two years)

My reasoning goes as a follows:

* if lein-nvd can inspect the dependency tree, it means lein-nvd is in the classpath
* lein-nvd _shouldn't_ be in the analysed classpath, because nvd-clojure itself has many java dependencies, which affect a given project's transitive dep tree calculation, and therefore the CVE analysis.

So, by offering this functionality one would inherently favor false positives/negatives and other bugs related to classpath interference. I don't think we should make the wrong thing easy/attractive (i.e. attaching features to it).

This would be a simple alternative:

```bash
#!/usr/bin/env bash
set -Euxo pipefail

nvd_check(){
  # perform a nvd check following https://github.com/rm-hull/lein-nvd/tree/2493010bb61ea1cbd84a8f18ead45fe0ea2a874d#avoiding-classpath-interference
}

nvd_check
success=$?

if ! $success; then
  # print extra information:
  lein deps :tree
fi

exit $success
```

i.e., one can have a simple script for CI, where `lein deps :tree` is printed informatively whenever lein-nvd fails.

...It's not fancy but my humble recommendation is that for a security-oriented tool, convenience goes second.

Hope it helps!

**Comment by vemv** [comment]
I'll close this PR in face of the rationale shared above. In a close future I intent to deprecate all usages of nvd-clojure that are error-prone - quite a lot of issues have been reported because of those older patterns.

However we should document how to satisfy this reporting need anyway (as reflected in the snippet above).

**Pull request closed without merging**
